@BASE = http://localhost:4000/token
@REFRESH = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ODdiMDgxOWI0MjdhNjRhNjQwY2NlZSIsImlhdCI6MTY4NjY0MTg3M30.T3fXBObtCn-iVZTxjGmXQKh5TwIsuvVJyrcvk-YFgyk"

# Generate session tokens
POST {{BASE}}/
Content-Type: application/json

{ "id": "6487b0819b427a64a640ccee" }

###
# Validate access token
POST {{BASE}}/access/valid
Content-Type: application/json

{"refresh": "{{REFRESH}}"}